### ISSUE TITLE
Support Runtime

### ISSUE THREAD

**Issue by orangeagain** [idbrii/unity-navgen#4]
I found "NavLinkGenerator_Editor : Editor" only in editor, support runtime generate in code,please.

**Comment by idbrii** [comment]
I partially wrote unity-navgen thinking it would be good to have a solution that clearly didn't ship in your game. A tool to help you setup your navigation mesh but your runtime entirely depended on Unity's code.

Runtime generation would be neat, but at this point I don't think the results are good enough. unity-navgen is good for getting navlinks into a level and tweaking the results (esp, adding new manual links) to produce polished results. I don't think it's good enough to 100% rely on the results for runtime gameplay.

Additionally, I think runtime link generation is best performed by generating links while generating/modifying geo. For level gen, your generator has much better knowledge of how the geo fits together (or at least you can build that in). For dropping in or removing geo (a building falls over), you'd be better served putting navlinks on the objects being added into the level.  So I think navgen would always generate mediocre results compared to using your geo modifying code to generate navlinks.

Regardless, thanks for checking out the project!
