### ISSUE TITLE
Compatible with OffMeshLink

### ISSUE THREAD

**Issue by orangeagain** [idbrii/unity-navgen#5]
Is there plan to Compatible OffMeshLink?
Or I pull requests

**Comment by idbrii** [comment]
No plan. OffMeshLink is the old way of creating nav links. [Unity's
NavMeshComponents](https://github.com/Unity-Technologies/NavMeshComponents) provides NavMeshLink which is the new way. This package expects you to have NavMeshComponents and is only for the new method.
